// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"github.com/jackc/pgtype"
)

type Account struct {
	ID   int32
	Name string
}

type Ledger struct {
	ID          int32
	Description string
	Amount      pgtype.Numeric
	Credit      int32
	Debit       int32
}
